#!/usr/bin/env python3.12
"""Create a compact Senior Portfolio Manager recap from a BoltNews briefing.

The cron agent's final Telegram message is generated by Hermes, not this repo.
This script gives both humans and cron prompts a deterministic, checked recap
artifact to quote after validation/deploy instead of improvising from memory.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DEFAULT_MAX_CHARS = 1200
REQUIRED_LABEL = "## Senior PM Recap"

# Sections most likely to contain the portfolio-relevant top line by run mode.
PRIMARY_SECTION_HINTS = {
    "pre-market": [
        "Futures and Current Market Snapshot",
        "Overnight Top Developments",
        "Today's Risk Map",
    ],
    "post-market": [
        "Closing Market Snapshot",
        "Why Markets Moved",
        "Cross-Asset Confirmation or Divergence",
        "Tomorrow Setup",
    ],
    "weekend": [
        "Weekly Market Scoreboard",
        "The Week's Core Narrative",
        "Next Week Playbook",
    ],
    "weekly": [
        "Weekly Executive Summary",
        "Dominant Cross-Asset Narrative",
        "Contrarian Flags and Underpriced Risks",
    ],
}


def _strip_inline_markdown(text: str) -> str:
    """Keep Telegram-friendly text while removing noisy markdown wrappers."""
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"[`*_]+", "", text)
    return re.sub(r"\s+", " ", text).strip()


def _sections(markdown: str) -> dict[str, str]:
    """Return {heading: body} for H1/H2/H3 sections."""
    matches = list(re.finditer(r"^#{1,3}\s+(.+?)\s*$", markdown, re.MULTILINE))
    out: dict[str, str] = {}
    for idx, match in enumerate(matches):
        heading = _strip_inline_markdown(match.group(1).strip().strip("#"))
        start = match.end()
        end = matches[idx + 1].start() if idx + 1 < len(matches) else len(markdown)
        out[heading] = markdown[start:end].strip()
    return out


def _candidate_lines(markdown: str, mode: str) -> list[str]:
    """Pull high-signal lines from the most PM-relevant sections first."""
    sections = _sections(markdown)
    bodies: list[str] = []
    for hint in PRIMARY_SECTION_HINTS.get(mode, []):
        for heading, body in sections.items():
            if heading.lower() == hint.lower():
                bodies.append(body)
                break
    if not bodies:
        bodies = [markdown]

    lines: list[str] = []
    for body in bodies:
        for raw in body.splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or line == "---":
                continue
            # Tables are useful in the dashboard, but raw table rows make poor
            # Telegram recaps ("Index — Close — Change" without context). Let
            # prose/bullets carry the PM summary instead.
            if line.startswith("|"):
                continue
            # Convert bullets into compact natural language snippets.
            line = line.strip("- ")
            line = _strip_inline_markdown(line)
            if len(line) >= 35 and not line.lower().startswith("source notes"):
                lines.append(line)
    return lines


def build_recap(markdown: str, mode: str, max_chars: int = DEFAULT_MAX_CHARS) -> str:
    """Build a compact recap with tape, drivers, cross-asset read, and watch item."""
    mode_label = mode.replace("-", " ").title()
    candidates = _candidate_lines(markdown, mode)
    if not candidates:
        raise ValueError("briefing has no substantive lines to recap")

    bullets: list[str] = []
    seen: set[str] = set()
    for line in candidates:
        key = re.sub(r"[^a-z0-9]+", "", line.lower())[:120]
        if key in seen:
            continue
        seen.add(key)
        bullets.append(line)
        if len(bullets) >= 5:
            break

    recap_lines = [REQUIRED_LABEL, f"**{mode_label}:** compact portfolio-manager recap."]
    labels = ["Tape", "Driver", "Cross-asset read", "Positioning/risk", "Next watch"]
    for label, line in zip(labels, bullets):
        recap_lines.append(f"- **{label}:** {line}")

    recap = "\n".join(recap_lines).strip()
    if len(recap) <= max_chars:
        return recap

    # Hard cap for Telegram readability; preserve whole bullets where possible.
    capped = recap_lines[:2]
    for line in recap_lines[2:]:
        if len("\n".join(capped + [line])) > max_chars - 1:
            break
        capped.append(line)
    text = "\n".join(capped).rstrip()
    return text if len(text) <= max_chars else text[: max_chars - 1].rstrip() + "…"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate compact Senior PM recap from briefing.md")
    parser.add_argument("--briefing", type=Path, required=True)
    parser.add_argument("--mode", choices=["pre-market", "post-market", "weekend", "weekly"], required=True)
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--max-chars", type=int, default=DEFAULT_MAX_CHARS)
    args = parser.parse_args()

    if not args.briefing.exists() or args.briefing.stat().st_size < 500:
        print(f"ERROR: briefing missing or too small: {args.briefing}", file=sys.stderr)
        raise SystemExit(1)

    recap = build_recap(args.briefing.read_text(errors="replace"), args.mode, args.max_chars)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(recap + "\n")
    print(recap)


if __name__ == "__main__":
    main()
